name: CI
on:
  pull_request:
    paths:
      - .github/workflows/ci.yaml
      - pom.xml
      - "**/src/**"

defaults:
  run:
    shell: bash

env:
  GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}

jobs:
  # TO DEFINE
  # code check job
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github
          settings-path: ${{ github.workspace }}
      - run: mvn -B clean install --settings settings.xml
