name: publish
on:
  push:
    tags:
      - "v*.*.*"

env:
  GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGES }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: set version from tag
        run: mvn -B versions:set -DnewVersion=${GITHUB_REF#refs/tags/v}
      - name: build and deploy
        run: mvn -B clean deploy --settings settings.xml
